### ISSUE TITLE
Support dynamic python switching

### ISSUE THREAD

**Issue by rarkins** [renovatebot/docker-pipenv#18]
`pipenv` gives users the ability to specify an exact version of Python that must be used. e.g. `python_full_version = "3.7.5"`. If `pipenv` runs and the underlying `python` does not match, then it will fail, e.g.

```
Command failed: docker run --rm -v "/mnt/renovate/gh/org/project":"/mnt/renovate/gh/alan-eu/alan-backend" -v "/tmp/renovate-cache/others/pipenv":"/tmp/renovate-cache/others/pipenv" -e LC_ALL -e LANG -e PIPENV_CACHE_DIR -w "/mnt/renovate/gh/org/project" renovate/pipenv pipenv lock
Warning: Python 3.7.5 was not found on your system…
You can specify specific versions of Python with:
  $ pipenv --python path/to/python
```

I'm wondering if we could install *every* version of python (or at least every version we think might be used) using `pyenv` and then switch it at runtime.

**Comment by viceice** [comment]
see renovatebot/renovate#6036
